ewatch/early/urls.py
# FROM REPORT

from django.conf.urls import url

from . import views

app_name = 'early'
urlpatterns = [
    # ex: /early/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # ex: /early/view/2/
    # url(r'^view/(?P<pk>[0-9]+)/$', views.ViewView.as_view(), name='view'),

    # ex: /early/view/CL_BACKUP/
    url(r'^view/(?P<group>\S+)/$', views.view, name='view'),

    # ex: /early/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    ]

ewatch/ewatch/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^early/', include('early.urls')),
    url(r'^admin/', admin.site.urls),
]

ewatch/early/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.db import models
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible  # only if you need to support Python 2
class Country(models.Model):
    country_text = models.CharField(max_length=200)

    def __str__(self):
        return self.country_text

@python_2_unicode_compatible  # only if you need to support Python 2
class View(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    view_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.view_text

ewatch/early/views.py
# -*- coding: iso-8859-15 -*-

from __future__ import unicode_literals
from __future__ import print_function


from django.shortcuts import render

# Incorporo mis utilitarios de Livestatus

# from utils.testing import a_function
from utils.group_services import group_services, show_group_services_data, show_cpu_load, show_disk, show_memory
from utils.live_utils import  HostsGroup, ServiceStateHist, HostWarningAndCriticalAlerts
# from utils.live_utils import LV_Connect, HostsGroup, ServiceStateHist, HostWarningAndCriticalAlerts, GroupsDictionary
from utils.state_class import HostState, GroupState
from utils.connection_class import Connection#, ShowSetAsOrderedList


# FROM REPORT

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.template import loader

from .models import Country, View

from operator import itemgetter, attrgetter

country_prefix = None

class IndexView(generic.ListView):
    template_name = 'early/index.html'

    def get_queryset(self):
        """Return the list of countries."""
        return Country.objects.order_by('country_text')

class DetailView(generic.DetailView):
    model = Country
    template_name = 'early/detail.html'

    def get_context_data(self, **kwargs):
        global country_prefix
        context = super(DetailView, self).get_context_data(**kwargs)

        # print("DetailView: pk[%s]" % (self.kwargs['pk']))

        country_dict = {r'CHILE':r'CL_', r'ARGENTINA':r'AR_', r'PERU':r'PE_',
                        r'COLOMBIA':r'CO_', r'BRASIL':r'BR_',}

        # Se va a buscar a la base de datos el objeto del modelo
        # Country, asociado a la pk recibida.

        _pk = self.kwargs['pk']
        c = Country.objects.get(pk=_pk)
        _country = c.country_text
        # print( _country )

        # Se obtiene el prefijo asociado al pais.

        if _country in country_dict:
            country_prefix = country_dict[ _country ]
        else:
            print("views.py: class DetailView: key[%s] no existe en country_dict !!!" % (_country))
            country_prefix = None
        # print( country_prefix )

        connection = Connection() # It takes a 0m1.338s, to load it.
        # connection.show()

        group_set = set()
        if country_prefix in connection.country_dict:
            groups_dict = connection.country_dict[country_prefix].group_dict
            for groupname in groups_dict:
                group_set.add( groups_dict[groupname] )

        context['country_text'] = _country

        # OJO: Debería convertir set en lista y ordenarla y pasar a template la lista ...
        context['group_list'] = sorted(list(group_set), key=attrgetter('groupname'))

        return context


class ResultsView(generic.DetailView):
    model = Country
    template_name = 'early/results.html'


def view(request, group):
    global country_prefix

    # return HttpResponse("You're looking at group %s." % group)
    template = loader.get_template('early/view.html')

    print("get_context_data: group[%s]" % (group))

    connection = Connection() # It takes a 0m1.338s, to load it.

    host_dict = connection.country_dict[country_prefix].group_dict[group].host_dict

    hosts_list = []
    group_state = GroupState( group )
    for hostname in host_dict:
        print( host_dict[hostname].hostname )
        Host = HostState( host_dict[hostname].hostname )
        Host.check_cpu( host_dict[hostname].conn )
        Host.check_disk( host_dict[hostname].conn )
        Host.check_memory( host_dict[hostname].conn )
        Host.check_alerts( host_dict[hostname].conn )
        hosts_list.append( Host )
        group_state.check_host_state( Host.state )        

    context = {
        # 'hosts': hosts_list,
        'hosts': sorted(hosts_list, key=attrgetter('hostname')),
        'group': group_state,
    }

    return HttpResponse(template.render(context, request))

ewatch/early/templates/early/detail.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Reporte Sanidad</title>

		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'early/style.css' %}" />
		
	</head>
	<body>

		<h1>INFORME DE ESTADO DE SALUD PLATAFORMA</h1>

		<section class="container">

			<h1>{{ country_text }}</h1>

			{% if group_list %}

				<select size="1" name="links" onchange="window.location.href=this.value;">

					<option selected disabled>ESCOJA UNA OPCION</option>

					{% for view in group_list %}
						<option value="{% url 'early:view' view.groupname %}">{{ view.groupname }}</option>
					{% endfor %}
				</select>
				<br>
				<br>

			{% endif %}

			<a href="{% url 'early:index' %}">Revisar otra vista ?</a>

		</section>

	</body>
</html>

ewatch/early/templates/early/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Reporte Sanidad</title>

		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'early/style.css' %}" />
		
	</head>
	<body>

		<h1>INFORME DE ESTADO DE SALUD PLATAFORMA</h1>

		<section class="container">

			{% if country_list %}
			    <ul>
			    {% for country in country_list %}
			        <li><a href="{% url 'early:detail' country.id %}">{{ country.country_text }}</a></li>
			    {% endfor %}
			    </ul>
			{% else %}
			    <p>No countries are available.</p>
			{% endif %}

		</section>


	</body>
</html>

ewatch/early/templates/early/results.html
<h1>{{ country.country_text }}</h1>

<ul>
{% for view in country.view_set.all %}
    <li>{{ view.view_text }}</li>
{% endfor %}
</ul>

<a href="{% url 'early:detail' country.id %}">Revisar nuevamente ?</a>

ewatch/early/templates/early/view.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Reporte Sanidad</title>

		{% load static %}

		{% if group.color == 'green' %}
			<link rel="stylesheet" type="text/css" href="{% static 'early/style_green.css' %}" />
		{% elif group.color == 'red' %}
			<link rel="stylesheet" type="text/css" href="{% static 'early/style_red.css' %}" />
		{% else %}
			<link rel="stylesheet" type="text/css" href="{% static 'early/style_yellow.css' %}" />
		{% endif %}

		<link rel="stylesheet" type="text/css" href="{% static 'early/style.css' %}" />
		
	</head>
	<body>

		<h1>INFORME DE ESTADO DE SALUD PLATAFORMA</h1>

		<section class="container">

			<h1 style="color: #4AC1E8">Resumen General</h1>

			<section>

				<aside class="aside-left">
					<div class="background-image">
						<h1 style="color: {{ group.color }};margin-left: 4em;">{{ group.groupname }}</h1>
					</div>
				</aside>

				<aside class="aside-right">
					<p> {{ group.summary }} </p>
					<strong><p> {{ group.action }} </p></strong>
				</aside>

			</section>

			{% load early_extras %}

			{% block content %}

				{% for host in hosts %}

				    {#<strong><font color={{ host.color }} size="4">{{ host.hostname }}</font></strong>#}
				    <h2 style="color: {{ host.color }};">{{ host.hostname }}</h2>

					<table>
						<caption>Detalle de los recursos</caption>
						<thead>
							<tr>
								<th scope="col">State</th>
								<th scope="col">Service</th>
								<th scope="col">Status detail</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="ok">OK</td>
								<td>CPU utilization</td>
								<td>{{ host.cpu }}</td>
							</tr>
							<tr>
								<td class="ok">OK</td>
								<td>Disk IO SUMMARY</td>
								<td>{{ host.disk }}</td>
							</tr>
							<tr>
								<td class="ok">OK</td>
								<td>Memory</td>
								<td>{{ host.memory }}</td>
							</tr>
						</tbody>
					</table>
					<br>

					{% if host.alerts %}

						<table>
							<caption>Alertas</caption>
							<thead>
								<tr>
									<th scope="col">State</th>
									<th scope="col">Status detail</th>
								</tr>
							</thead>
							<tbody>
								{% for alert in host.alerts %}
									<tr>
										<td bgcolor={{ alert|alert_color }}>{{ alert|text_color }}</td>
										<td bgcolor={{ alert|alert_color }}>{{ alert }}</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
						<br>

					{% endif %}
					{#<br>#}

				{% endfor %}

			{% endblock %}

			<a href="{% url 'early:index' %}">Revisar otra vista ?</a>

		</section>

	</body>
</html>